import { Industry, OrganizationSize } from '@/generated/prisma/enums'

export const industryMap: Record<Industry, string> = {
  [Industry.ACCOUNTING]: 'Accounting',
  [Industry.ADVERTISING]: 'Advertising',
  [Industry.AGRICULTURE]: 'Agriculture',
  [Industry.AIRLINES_AVIATION]: 'Airlines & Aviation',
  [Industry.APPAREL_FASHION]: 'Apparel & Fashion',
  [Industry.ARCHITECTURE_PLANNING]: 'Architecture & Planning',
  [Industry.AUTOMOTIVE]: 'Automotive',
  [Industry.BANKING]: 'Banking',
  [Industry.BIOTECHNOLOGY]: 'Biotechnology',
  [Industry.BROADCAST_MEDIA]: 'Broadcast Media',
  [Industry.CHEMICALS]: 'Chemicals',
  [Industry.CIVIL_ENGINEERING]: 'Civil Engineering',
  [Industry.COMPUTER_HARDWARE]: 'Computer Hardware',
  [Industry.COMPUTER_SOFTWARE]: 'Computer Software',
  [Industry.CONSTRUCTION]: 'Construction',
  [Industry.CONSULTING]: 'Consulting',
  [Industry.CONSUMER_ELECTRONICS]: 'Consumer Electronics',
  [Industry.CONSUMER_GOODS]: 'Consumer Goods',
  [Industry.EDUCATION]: 'Education',
  [Industry.ELECTRICAL_ELECTRONIC_MANUFACTURING]:
    'Electrical/Electronic Manufacturing',
  [Industry.ENERGY]: 'Energy',
  [Industry.ENTERTAINMENT]: 'Entertainment',
  [Industry.ENVIRONMENTAL_SERVICES]: 'Environmental Services',
  [Industry.FINANCIAL_SERVICES]: 'Financial Services',
  [Industry.FOOD_BEVERAGES]: 'Food & Beverages',
  [Industry.GOVERNMENT_ADMINISTRATION]: 'Government Administration',
  [Industry.HEALTHCARE]: 'Healthcare',
  [Industry.HOSPITALITY]: 'Hospitality',
  [Industry.HUMAN_RESOURCES]: 'Human Resources',
  [Industry.INDUSTRIAL_AUTOMATION]: 'Industrial Automation',
  [Industry.INFORMATION_SERVICES]: 'Information Services',
  [Industry.INFORMATION_TECHNOLOGY]: 'Information Technology',
  [Industry.INSURANCE]: 'Insurance',
  [Industry.INTERNET]: 'Internet',
  [Industry.INVESTMENT_BANKING]: 'Investment Banking',
  [Industry.LAW_PRACTICE]: 'Law Practice',
  [Industry.LEGAL_SERVICES]: 'Legal Services',
  [Industry.LOGISTICS_SUPPLY_CHAIN]: 'Logistics & Supply Chain',
  [Industry.MANUFACTURING]: 'Manufacturing',
  [Industry.MARKETING]: 'Marketing',
  [Industry.MEDIA]: 'Media',
  [Industry.MEDICAL_DEVICES]: 'Medical Devices',
  [Industry.MINING_METALS]: 'Mining & Metals',
  [Industry.NONPROFIT]: 'Nonprofit Organization Management',
  [Industry.OIL_ENERGY]: 'Oil & Energy',
  [Industry.PHARMACEUTICALS]: 'Pharmaceuticals',
  [Industry.PUBLIC_RELATIONS]: 'Public Relations & Communications',
  [Industry.REAL_ESTATE]: 'Real Estate',
  [Industry.RESEARCH]: 'Research',
  [Industry.RESTAURANTS]: 'Restaurants',
  [Industry.RETAIL]: 'Retail',
  [Industry.SPORTS]: 'Sports',
  [Industry.TELECOMMUNICATIONS]: 'Telecommunications',
  [Industry.TRANSPORTATION]: 'Transportation',
  [Industry.UTILITIES]: 'Utilities',
  [Industry.VENTURE_CAPITAL]: 'Venture Capital & Private Equity',
  [Industry.WHOLESALE]: 'Wholesale',
}

export const organizationSizeMap: Record<OrganizationSize, string> = {
  [OrganizationSize.SELF_EMPLOYED]: 'Self-employed',
  [OrganizationSize.ONE_TO_TEN]: '1-10 employees',
  [OrganizationSize.ELEVEN_TO_FIFTY]: '11-50 employees',
  [OrganizationSize.FIFTY_ONE_TO_TWO_HUNDRED]: '51-200 employees',
  [OrganizationSize.TWO_HUNDRED_ONE_TO_FIVE_HUNDRED]: '201-500 employees',
  [OrganizationSize.FIVE_HUNDRED_ONE_TO_ONE_THOUSAND]: '501-1,000 employees',
  [OrganizationSize.ONE_THOUSAND_ONE_TO_FIVE_THOUSAND]: '1,001-5,000 employees',
  [OrganizationSize.FIVE_THOUSAND_ONE_TO_TEN_THOUSAND]:
    '5,001-10,000 employees',
  [OrganizationSize.TEN_THOUSAND_PLUS]: '10,001+ employees',
}
